app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

# from django.shortcuts import render


urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("api/v1/", include("authentication.urls")),
    path("", views.home, name="home"),
    path("", include("brands.urls")),
    path("", include("categories.urls")),
    path("", include("suppliers.urls")),
    path("", include("inflows.urls")),
    path("", include("outflows.urls")),
    path("", include("products.urls")),
]

inflows/models.py
from django.db import models
from products.models import Product
from suppliers.models import Supplier

# Create your models here.


class Inflow(models.Model):
    supplier = models.ForeignKey(
        to=Supplier, on_delete=models.PROTECT, related_name="inflows"
    )
    product = models.ForeignKey(
        to=Product, on_delete=models.PROTECT, related_name="inflows"
    )
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return str(self.product)

outflows/models.py
from django.db import models
from products.models import Product

# Create your models here.


class Outflow(models.Model):
    product = models.ForeignKey(
        to=Product, on_delete=models.PROTECT, related_name="outflows"
    )
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return str(self.product)

products/models.py
from django.db import models
from categories.models import Category
from brands.models import Brand

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=500)
    category = models.ForeignKey(
        to=Category, on_delete=models.PROTECT, related_name="products"
    )
    brand = models.ForeignKey(
        to=Brand, on_delete=models.PROTECT, related_name="products"
    )
    description = models.TextField(null=True, blank=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title

app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme='light'>
<head>
    {% block head %}
      
    {% endblock head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include "components/_header.html" %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            {% if user.is_authenticated%}
                {% include "components/_sidebar.html" %}
            {% endif %}
            <div class="col py-3">
                <div class="container mt-4">
                    <main>
                        {% block content %}
                        
                        {% endblock content %}
                    </main>
                </div>
            </div>
        </div>
    </div>
    {% include "components/_footer.html" %}
</body>
</html>

app/templates/home.html
{% extends "base.html" %}


{% block title %}
  SGE - Home
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
<script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
{% endblock head %}


{% block content %}
<script>
    document.addEventListener("DOMContentLoaded", function(){
    var dailySalesData = JSON.parse('{{daily_sales_data|safe}}')
    var dailySalesQuantityData = JSON.parse('{{daily_sales_quantity_data|safe}}')
    var productCountByCategory = JSON.parse('{{product_count_by_category|safe}}')
    var productCountByBrand = JSON.parse('{{product_count_by_brand|safe}}')

    new Chartist.Line('#dailySalesChart', {
        labels: dailySalesData.dates,
        series: [
            dailySalesData.values,
            
        ]
    }, {
        low:10,
        showArea: true,
        fullWidth: true,
        chartPadding: {
            right: 0
        }
    });
    new Chartist.Bar('#dailySalesQuantityChart', {
        labels: dailySalesQuantityData.dates,
        series: [
            dailySalesQuantityData.quantities,
            
        ]
    }, {
        high: 10,
        low:0,
        showArea: true,
        fullWidth: true,
        chartPadding: {
            right: 0
        },
        
    });
    new Chartist.Bar('#productByCategoryChart', {
        labels: productCountByCategory.names,
        series: [
            productCountByCategory.quantities,
        ]
    }, {
        distributedSeries: true
    });

    
    var data = {
        labels: productCountByBrand.names,
        series: productCountByBrand.quantities
      };
      
    var options = {
        labelInterpolationFnc: function(value) {
          return value[0]
        }
      };
      
    var responsiveOptions = [
        ['screen and (min-width: 640px)', {
          chartPadding: 30,
          labelOffset: 100,
          labelDirection: 'explode',
          labelInterpolationFnc: function(value) {
            return value;
          }
        }],
        ['screen and (min-width: 1024px)', {
          labelOffset: 40,
          chartPadding: 10
        }]
      ];
      
    new Chartist.Pie('#productByBrandChart', data, options, responsiveOptions);
      
});
</script>

{% if perms.products.view_product and perms.inflows.view_inflow %}
  {% include "components/_product_metrics.html" %}
{% endif %}  

{% if perms.outflows.view_outflow %}
  {% include "components/_sales_metrics.html" %}
{% endif %}


  {% if perms.outflows.view_outflow %}
  <div class="row mt-4 justify-content-center">
    <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Valor de Vendas (Últimos 7 dias)</h5>
            <div class="ct-chart" id="dailySalesChart"></div>
        </div>
        
    <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Quantidade de Vendas Diárias</h5>
            <div class="ct-chart" id="dailySalesQuantityChart"></div>
    </div>
  </div>
  {% endif %}

  {% if perms.products.view_product %}
  <div class="row mt-4 justify-content-center">
    <div class="col-md-6 text-center">
        <h5 class="mb-3">Produtos por Categoria</h5>
            <div class="mt-4"></div>
            <div class="embed-responsive embed-responsive-1by1 ct-chart" style="width: 400px; display: inline-block;">
                <div class="embed-responsive-item" id="productByCategoryChart"></div>
            </div>
    </div>
        
    <div class="col-md-6 text-center">
        <h5 class="mb-3">Produtos por Marca</h5>
            <div class="mt-4"></div>
            <div class="embed-responsive embed-responsive-1by1 ct-chart" style="width: 400px; display: inline-block;">
                <div class="embed-responsive-item" id="productByBrandChart"></div>
            </div>
    </div>
  </div>
  {% endif %}

{% endblock content %}

app/templates/teste.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Virtual Assistant</title>
  <link rel="stylesheet" href="./styles.css">
</head>
<body>

  <header>
    <div class="container">
      <h1>Seu Assistente Virtual</h1>
      <nav>
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">Serviços</a></li>
          <li><a href="#">Sobre</a></li>
          <li><a href="#">Contato</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <section id="hero">
    <div class="container">
      <h2>Economize seu tempo com um assistente virtual.</h2>
      <p>Deixe que eu cuide das tarefas para que você possa se concentrar no que realmente importa.</p>
      <a href="#" class="button">Saiba mais</a>
    </div>
  </section>

  <section id="services">
    <div class="container">
      <h3>Nossos Serviços</h3>
      <div class="service-grid">
        <div class="service">
          <img src="placeholder-image.jpg" alt="Serviço 1">
          <h4>Gerenciamento de E-mail</h4>
          <p>Mantenha sua caixa de entrada organizada e eficiente.</p>
        </div>
        <div class="service">
          <img src="placeholder-image.jpg" alt="Serviço 2">
          <h4>Agendamento</h4>
          <p>Nunca mais perca um compromisso importante.</p>
        </div>
        <div class="service">
          <img src="placeholder-image.jpg" alt="Serviço 3">
          <h4>Assistência Administrativa</h4>
          <p>Suporte completo para suas tarefas administrativas.</p>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; 2025 Seu Assistente Virtual</p>
    </div>
  </footer>

</body>
</html>